{{- if .Values.postgres.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.postgres.name }}
  labels:
    {{- include "backend-service.labels" . | nindent 4 }}
spec:
  instances: {{ .Values.postgres.instances }}
  
  {{- if .Values.postgres.imageName }}
  imageName: {{ .Values.postgres.imageName }}
  {{- end }}
  
  # Bootstrap (initdb, recovery, etc.)
  bootstrap:
    {{- toYaml .Values.postgres.bootstrap | nindent 4 }}

  storage:
    size: {{ .Values.postgres.storage.size }}
    storageClass: {{ .Values.postgres.storage.class }}
  
  resources:
    {{- toYaml .Values.postgres.resources | nindent 4 }}
  
  postgresql:
    {{- toYaml .Values.postgres.postgresql | nindent 4 }}

  monitoring:
    {{- toYaml .Values.postgres.monitoring | nindent 4 }}

  {{- if .Values.postgres.backup.enabled }}
  backup:
    retentionPolicy: {{ .Values.postgres.backup.retentionPolicy | quote }}
    {{- if .Values.postgres.backup.barmanObjectStore }}
    barmanObjectStore:
      {{- toYaml .Values.postgres.backup.barmanObjectStore | nindent 6 }}
    {{- end }}
  {{- end }}

  {{- with .Values.postgres.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.postgres.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.postgres.tolerations }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
